### ISSUE TITLE
How to try it ?

### ISSUE THREAD

**Issue by vindarel** [kaleissin/django-library#1]
Hi,
I'm relatively new to Django. I already built my own models/templates/forms, but you are providing an _app_, and I can't find how to integrate it in my own project. I was expecting a manage.py.
  I tried a bit with no success and didn't find explicit doc on the web.
  Could you add a few words about this in your README ?

  That's the only way I found to contact you.

 Thanks !

**Comment by kaleissin** [comment]
Thx for writing! You get the app from pypi, for instance with "pip install django-library'. Then you append to INSTALLED_APPS in your django settings-file:

INSTALLED_APPS = (
 .. lots of other things..
 'library',
)

The reason there is no manage.py is that I no longer use it directly but use django-admin.py instead. 

I'll beef up the README a little.

**Comment by vindarel** [comment]
And thanks for replying!
I tried a bit more:
- I installed django-library with pip
- I started a new django project and a new app
- I added 'library' in my app's settings.py
- I added an url in my app's urls.py: "url(r'^library/',
  include('library.urls'))"
- I run the server and that's not enough: Django doesn't find the base
  template
- I copied the templates folder from 'homelibrary' and put it in my app's
  but that isnt enough

I then tried from within the vanilla homelibrary:
- run django-admin.py runserver
- but that throws some errors: "ImproperlyConfigured: Requested setting
  USE_I18N, but settings are not configured. You must either define the
  environment variable DJANGO_SETTINGS_MODULE or call settings.configure()
  before accessing settings."
  
  In homelibrary there's a whole 'settings' folder, instead of a simple
  settings.py file that comes with a new app. So I copied it to my app;  then
  I had to configure the environment variable DJANGO_SETTINGS_MODULE, which i
  did from within the terminal but it raises an import error, so it doesn't
  seem to be the right way. And the only occurence of DJANGO_SETTINGS_MODULE
  in your code appears in wsgi.py. I made it point to the new
  settings/[base|test].py but same error.
  i don't know when wsgi interferes.

I didn't investigate any further and didn't re-read django docs. I guess
the installation should be straightforward, so I'll wait for the readme :)

Looking forward to hack on that project :)
thanks

2013/11/14 kaleissin notifications@github.com

**Comment by kaleissin** [comment]
Thanks for doing your homework =) I've stopped expecting that </old fogey>

Templates when just using the app: Do you have the app-template loader
('django.template.loaders.app_directories.Loader' in 1.6) in
TEMPLATE_LOADERS?

To use the settings from homelibrary you need homelibrary's parent dir to
be on the path (the homedir that is). Then DJANGO_SETTINGS_MODULE should be
"homelibrary.settings.local" while you develop, "homelibrary.settings.test"
for unittests, "homelibrary.settings.production" otherwise. The calculated
filepaths in the settings-file depends on the structure being as it is.

I notice that django-library doesn't follow how I do things these days,
with a magic Makefile. I'll add that. The goal of the (unfinished) file
structure is to be able to drop the entire thing (django-library)
somewhere, point apache WSGIScriptAlias to wsgi.py in homelibrary, alias
/media and /static in apache to the right dirs inside django-library and
just restart apache.

django-admin.py needs a couple flags if things aren't officially on the
python-path: for instance

```
--settings=homelibrary.settings.local
```

--pythonpath=/path/to/django-library/src

 HTH, and I'll adapt the Makefile (
https://github.com/kaleissin/django-makefile) and pop it in.

**Comment by kaleissin** [comment]
You could try copying homelibrary/templates/base.html to the root of
whatever templates-directory that it _can_ find. Hm, wonder if that
custom/tradition is sufficiently documented at djangoproject.com itself...

**Comment by vindarel** [comment]
Hi,
so I carried on trying to figure it out and I thought I might give you some
news :)
i tried both «using the app» and «test driving the example». It required a
bit more configuration than documented (even though it's classical Django
config, a beginner would appreciate to read a word about it => I'll come
back about that another day).
  With «using the app» I tried to migrate the db with South but faced the
message «the library does not appear to use migrations». I'm reading the
doc.
  When testing from scratch, I tried to run "south migrate", but I need to
sync the db first with "django-admin syncdb", and it won't find settings.
So I'm trying (again) to give them on the command line.

  So I'll carry on digging around, but if you have the right command under
your eyes I'd appreciate to know it :)

see you

2013/11/19 kaleissin notifications@github.com

**Comment by kaleissin** [comment]
What exact error did you get with south? Was there also an exception?

Are you on windows, mac, or linux, btw?

To set settings you can either use an environment-variable:

```
DJANGO_SETTINGS_MODULE=homelibrary.settings.production django-admin.py
```

syncdb

or an argument to the command:

```
django-admin.py syncdb --settings=homelibrary.settings.production
```

In addition, if the directory homelibrary (or whatever your project is
called) is not on the python path, check with:

```
 python -c "import sys; print 'sys.path:', sys.path
```

then you need to add it, with the environment-variable PYTHONPATH or the
argument --pythonpath

In the case of just cloning the entire repo and standing inside it, the
path you need to add is something ala. ./src/

The makefile sets this stuff for you btw.

K

**Comment by vindarel** [comment]
OMG it was so simple. I ran again the 3 make commands from the README but
_from the base directory_…
Really nice Makefile indeed.
So now, let's speak about good stuff, about development (I have plenty of
ideas for you ;) )
thx again

ps: I'm on Linux (I tried on Ubuntu so far)

2013/12/5 kaleissin notifications@github.com

**Comment by kaleissin** [comment]
The safe way with make is always to cd into the dir with the Makefile. It can be hard for unix-files to know their own absolute location: try googling for "shellscript discover directory", w/o the quotes. This is because with fancy mounts and symlinks and hardlinks, a file can exist in several places at the same time, and it is only while called/accessed that the caller/accessor sees it at a specific location. Delete it while it is being called/accessed and it will still exist for the caller/accessor until the call/access finishes/completes, and it can be resurrected until this happens. Unix files are all Schrödinger's files :)

The library is based on an legacy system written in a single file of php. The django-project, of which "homelibrary" is a sanitized version, started out feature-equivalent with that, which was very, very simple and stored the books in a flat file.
